Getting data from: https://data.illinois.gov/dataset/professional-licensing/resource/beef79ab-b679-4b0a-960a-05c218a619ba

In [18]:
save_file = '/Users/jnaiman/Downloads/tmp/license_records_1000000.csv'

In [2]:
import urllib
import json
import pandas as pd

In [7]:
#url = 'https://data.illinois.gov/api/3/action/datastore_search?resource_id=beef79ab-b679-4b0a-960a-05c218a619ba&limit=5&q=title:jones'  
#url = 'https://data.illinois.gov/api/3/action/datastore_search?resource_id=beef79ab-b679-4b0a-960a-05c218a619ba&limit=5'  
#url = 'https://data.illinois.gov/api/3/action/datastore_search?resource_id=beef79ab-b679-4b0a-960a-05c218a619ba&limit=100000'  
url = 'https://data.illinois.gov/api/3/action/datastore_search?resource_id=beef79ab-b679-4b0a-960a-05c218a619ba&limit=1000000'  
fileobj = urllib.request.urlopen(url)
data = fileobj.read().decode('utf-8')

In [8]:
j = json.loads(data)

In [9]:
df = pd.DataFrame(j['result']['records'])

In [10]:
df

,_id,License Type,Description,License Number,License Status,Business,Title,First Name,Middle,Last Name,...,Specialty/Qualifier,Controlled Substance Schedule,Delegated Controlled Substance Schedule,Ever Disciplined,LastModifiedDate,Case Number,Action,Discipline Start Date,Discipline End Date,Discipline Reason
0,279023,APPRAISAL,STATE LICENSED REAL ESTATE APPRAISER,554007152,EXPIRED,N,,KARON,M,HOFFMAN,...,None,None,None,N,10/01/2003,None,None,None,None,None
1,279024,APPRAISAL,STATE LICENSED REAL ESTATE APPRAISER,554007159,EXPIRED,N,,WILLIAM,T,BUCHER,...,None,None,None,N,10/01/2003,None,None,None,None,None
2,279025,APPRAISAL,STATE LICENSED REAL ESTATE APPRAISER,554007176,EXPIRED,N,,TIMOTHY,N,BRECOUNT,...,None,None,None,N,10/01/2003,None,None,None,None,None
3,279026,APPRAISAL,STATE LICENSED REAL ESTATE APPRAISER,554007177,EXPIRED,N,,MARY,K,KENDALL,...,None,None,None,N,10/01/2003,None,None,None,None,None
4,279027,APPRAISAL,STATE LICENSED REAL ESTATE APPRAISER,554007183,EXPIRED,N,,PATRICK,,DEFILIPPO,...,None,None,None,N,10/01/2003,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1279120,INTERIOR DESIGN,REGISTERED INTERIOR DESIGNER,161001406,INACTIVE,N,,ALLEN D,,MORENO,...,None,None,None,N,10/16/2005,None,None,None,None,None
999996,1279121,INTERIOR DESIGN,REGISTERED INTERIOR DESIGNER,161001425,NOT RENEWED,N,,LOUIS A,,MOHN,...,None,None,None,N,11/01/2017,None,None,None,None,None
999997,1279122,INTERIOR DESIGN,REGISTERED INTERIOR DESIGNER,161001427,NOT RENEWED,N,,DEANNA JOY,,BERMAN,...,None,None,None,N,11/13/2007,None,None,None,None,None
999998,1279123,INTERIOR DESIGN,REGISTERED INTERIOR DESIGNER,161001429,NOT RENEWED,N,,GRACE F,,BRADFORD,...,None,None,None,N,11/01/2017,None,None,None,None,None
999999,1279124,INTERIOR DESIGN,REGISTERED INTERIOR DESIGNER,161001431,NOT RENEWED,N,,JEROME I,,WILLIS,...,None,None,None,N,01/13/2020,None,None,None,None,None

In [11]:
#df.to_csv?

In [19]:
df.to_csv(save_file,index=False)

In [20]:
dfin = pd.read_csv(save_file)

/Users/jnaiman/opt/anaconda3/envs/DataViz/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (3,6,10,19) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [21]:
dfin.head()

,_id,License Type,Description,License Number,License Status,Business,Title,First Name,Middle,Last Name,...,Specialty/Qualifier,Controlled Substance Schedule,Delegated Controlled Substance Schedule,Ever Disciplined,LastModifiedDate,Case Number,Action,Discipline Start Date,Discipline End Date,Discipline Reason
0,279023,APPRAISAL,STATE LICENSED REAL ESTATE APPRAISER,554007152,EXPIRED,N,NaN,KARON,M,HOFFMAN,...,None,None,None,N,10/01/2003,None,None,None,None,None
1,279024,APPRAISAL,STATE LICENSED REAL ESTATE APPRAISER,554007159,EXPIRED,N,NaN,WILLIAM,T,BUCHER,...,None,None,None,N,10/01/2003,None,None,None,None,None
2,279025,APPRAISAL,STATE LICENSED REAL ESTATE APPRAISER,554007176,EXPIRED,N,NaN,TIMOTHY,N,BRECOUNT,...,None,None,None,N,10/01/2003,None,None,None,None,None
3,279026,APPRAISAL,STATE LICENSED REAL ESTATE APPRAISER,554007177,EXPIRED,N,NaN,MARY,K,KENDALL,...,None,None,None,N,10/01/2003,None,None,None,None,None
4,279027,APPRAISAL,STATE LICENSED REAL ESTATE APPRAISER,554007183,EXPIRED,N,NaN,PATRICK,NaN,DEFILIPPO,...,None,None,None,N,10/01/2003,None,None,None,None,None

In [15]:
dfin.columns

Index(['_id', 'License Type', 'Description', 'License Number',
       'License Status', 'Business', 'Title', 'First Name', 'Middle',
       'Last Name', 'Prefix', 'Suffix', 'Business Name', 'BusinessDBA',
       'Original Issue Date', 'Effective Date', 'Expiration Date', 'City',
       'State', 'Zip', 'County', 'Specialty/Qualifier',
       'Controlled Substance Schedule',
       'Delegated Controlled Substance Schedule', 'Ever Disciplined',
       'LastModifiedDate', 'Case Number', 'Action', 'Discipline Start Date',
       'Discipline End Date', 'Discipline Reason'],
      dtype='object')

In [16]:
dfin['Original Issue Date']

0         03/27/2002
1         03/27/2002
2         04/03/2002
3         04/03/2002
4         04/09/2002
             ...
999995    10/22/1992
999996    10/22/1992
999997    10/22/1992
999998    10/22/1992
999999    10/22/1992
Name: Original Issue Date, Length: 1000000, dtype: object

In [17]:
dfin['Expiration Date']

0         09/30/2003
1         09/30/2003
2         09/30/2003
3         09/30/2003
4         09/30/2003
             ...
999995    08/31/1995
999996    08/31/2017
999997    08/31/2007
999998    08/31/2017
999999    08/31/2019
Name: Expiration Date, Length: 1000000, dtype: object